services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: online-exam:prod
    container_name: online-exam-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: pgsql
      DB_HOST: db-postgres
      DB_PORT: "5432"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: hieu.buiquang
      MINIO_SECRET_KEY: Hieu2002113.
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION}
      RUN_MIGRATIONS: "true"
    ports:
      - "8000:80"
    networks:
      - hieubq-network

networks:
  hieubq-network:
    external: true



